twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        feature_three_forms: '%feature_three_forms%'

when@test:
    twig:
        strict_variables: true

when@prod:
    twig:
        globals:
            matomo:
                url: https://histologe.matomo.cloud/
                cdn: //cdn.matomo.cloud/histologe.matomo.cloud/matomo.js
                site_id: 16
