twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        feature_three_forms: '%feature_three_forms%'
        platform:
            url: '%base_url%'
        gitbook:
            faq: https://faq.stop-punaises.gouv.fr/

when@dev:
    twig:
        globals:
            matomo:
                url: null
                cdn: null
                site_id: '%matomo_site_id%'
                enable: '%matomo_enable%'

when@test:
    twig:
        strict_variables: true

when@prod:
    twig:
        globals:
            matomo:
                url: https://histologe.matomo.cloud/
                cdn: //cdn.matomo.cloud/histologe.matomo.cloud/matomo.js
                site_id: '%matomo_site_id%'
                enable: '%matomo_enable%'
